### ISSUE TITLE
Can still see stats after removing deck

### ISSUE THREAD

**Issue by GabrielSimbingyang** [AY2021S1-CS2103T-T09-4/tp#196]
Bug: Can still see that stats for the deck after removing said deck by CLICKING on the stats tabs

Not sure if this is a bug as the user is only supposed to interact with the commandline

Instructions: 
new deck
select 1
add w/p t/p
/play
p
/play
p
stats 1
remove 1
CLICK on stats

**Comment by geoboom** [comment]
Resolved. When click statistics panel it will default to show statistics **over all decks** rather than the most recently selected deck. :)
