### ISSUE TITLE
Update UG bugs

### ISSUE THREAD

**Issue by GabrielSimbingyang** [AY2021S1-CS2103T-T09-4/tp#212]
Finish fixing all of these bug by today before meeting. **Each of us can comment below a few bugs that we fix**

**DO these last**
- [x] 1. Inconsistent figure naming AND numbering (do this last)
- [x] 2. Chapter 6, 3, select a deck in chapter 5.2 jump links not working
- [x] 8. chapter 5.3.1 , 5.3.2 link is not working
- [x] 11. Chapter 6, play a game jump link is not working

**Do these first**
- [x] 1.5 Vignesh stuff in UG that are not yet completed

**Do these next**
- [x] 3. Remove java link in chapter 3
- [x] 4. add light bulb emoji in chapter 5.1.1 to remind users a deck is a list of entries
- [x] 5. Chapter 5.1.3, show user before and after selecting a deck that is populated with entries. Image 1: should show welcome tab, image 2: show entries tab after selecting deck
- [x] 6. Inconsistent naming of figure in 5.1.2
- [x] 6.5 Figure 8 is wrong, command box should be (empty?) instead of "new Japanese Words", figure 9 can be updated as well
- [x] 7. update play to /play in chapter 5.3
- [x] 9. Chapter 5.3.1 "note the slash" can have a exclamation mark emoji before hand
- [x] 10. Chapter 6, highlight the word "all"
- [x] 12. Add some FAQS to chapter 7
- [x] 13. Fix ALL stats images (they still have the last login field?)
- [x] 14. Add images for section 3, figure 8?  to 11

**Comment by GabrielSimbingyang** [comment]
Completed number 3,4,6,7,9,10

**Comment by MelanieNPS** [comment]
6.5 is not an issue, all images have this to show to show the user the command to type in

**Comment by MelanieNPS** [comment]
Issues 5, 8, 11, 12 & 13 fixed
Added more issues to the list

**Comment by geoboom** [comment]
resolved 2. Chapter 6, 3, select a deck in chapter 5.2 jump links not working

**Comment by GabrielSimbingyang** [comment]
Completed
