### ISSUE TITLE
Data Tracking

### ISSUE THREAD

**Issue by GabrielSimbingyang** [AY2021S1-CS2103T-T09-4/tp#64]
Track relevant user data such as:

1. Number of correctly answered flashcards
2. Previous scores
3. Average time taken in total
4. Time of quiz

As well as the following subtasks:
1. Tests
2. Update DG

**Comment by geoboom** [comment]
App-based statistics:
- [x] Statistics and StatisticsManager classes for app-based statistics (average time spent online, login/logout events w/ timestamps)
- [ ] Persist Statistics to file (v1.3.2)

As for deck/quiz based statistics I plan to add a few classes:

```js
QuestionAttempt {
    correctAnswer,
    yourAnswer,
    score
}

QuizAttempt {
    duration,
    takenAt,
    questionAttempts[QuestionAttempt]
}
```

And for the `Deck` class itself, I will enhance it by adding a `List<QuizPerformance>` to which `QuizPerformance` objects will be pushed after user submits quiz. This will be persisted to disk together with the Deck.

Overall statistics like averages can be computed when rendering takes place. I intend to do this by building a `DeckComparator` class. If performance becomes an issue, we can also compute the statistics after every quiz submission via:
```
average = (average * (n-1) + newScore) / n;
```

Where `n` is the number of quiz attempts.

That's all from me for now. Going to wrap this up by Friday night so I can spend Saturday writing documentation.
