### ISSUE TITLE
Find Command does not filter properly

### ISSUE THREAD

**Issue by MelanieNPS** [AY2021S1-CS2103T-T09-4/tp#86]
FInd command does not filter according to the predicate. Result is always 0. Gui updates accordingly and does not show anything. Logic/model issue

**Comment by geoboom** [comment]
**Steps to reproduce:**
Perform the following in order:
```
New deck
Add entry <word -> translation>
Close the program
Reopen
Select deck
Find entry
```

**Expected:**
- Finds the entry you searched for.

**Actual:**
- No entries found all the time.

**Possible reasons:**
- find command's filter by predicate might be causing the issue.

**Comment by MelanieNPS** [comment]
Hmm idt its find command filter. I checked the repo at the time when find command works, the code is still the same. 
If you add a deck and entries and try to filter, it works. But after closing the program and reopening, it doesnt

**Comment by geoboom** [comment]
~~Unfortunately I can't load the saved stuff in the json file so can't debug this atm ><~~

**Comment by MelanieNPS** [comment]
Issue with filtered list not updating in Deck.java when Deck.setEntries(...) is called in storage.
Resolved
