### ISSUE TITLE
Update UG and DG

### ISSUE THREAD

**Issue by GabrielSimbingyang** [AY2021S1-CS2103T-T09-4/tp#96]
Update the UG and DG, each member is to contribute at least 1 page (if I recall correctly)

**Comment by GabrielSimbingyang** [comment]
Hi everyone, 

This is my contribution to UG. I have written down the basic table of contents and necessary markdown language. If you need to create any new features (like links , jumps etc). you can just refer to the markdown language that I have written so far. However, I have also gone through the trouble to find a good cheat sheet you can all refer to below. 

**Please fill up your portion of the UG in the same style I have written and if you can't finish it, at least do half-ish**
Remember to attach your name!

Melanie:  The individual deck commands
Vignesh: The individual entry Commands
Georgie:  Introduction to Play, Statistics and Extra commands. Add FAQ

For Melanie and Vignesh:
Use this guide as a reference, I think they have done a goodjob:
https://github.com/AY1920S2-CS2103T-W17-1/main/blob/master/docs/UserGuide.adoc#creating-a-deck-create
https://github.com/AY1920S2-CS2103T-W16-2/main/blob/master/docs/UserGuide.adoc#closing-zerotoone-wong-chi-shan
https://github.com/AY1920S2-CS2103T-W16-1/main/blob/master/docs/UserGuide.adoc#tasklist-branson

Here is a easy cheatsheet to refer to:
https://github.com/tchapi/markdown-cheatsheet

**Comment by GabrielSimbingyang** [comment]
Edit DG:

I have edited the flashcard portion and the select command portion **at the bottom of the DG**. From what I can gather, it seems like most of the new additions to the DG will be at the bottom. 

From looking at other groups, I think our DG is honestly quite bad, so we need to redouble our efforts in the DG in future iterations

These are the following tasks for the each of you:

Melanie: Update UI components and use cases (don't need to spend too much time on it because you have already done a lot, just need to update the UI part because I saw some UI changes in the latest iteration and maybe 2-3 use cases)

Georgie: Update your validation component **including** updating the picture
Vignesh: Update memory **including** picture (super important so we can all understand how memory works)

Some reference DGS that I think are quite good:
https://github.com/AY2021S1-CS2103T-T09-3/tp/blob/master/docs/DeveloperGuide.md
https://github.com/AY1920S2-CS2103T-W16-2/main/blob/master/docs/DeveloperGuide.adoc

**Comment by geoboom** [comment]
Update validation:
- [x] Writeup
- [ ] Picture (not sure if my component is too trivial for a picture but I'll check again after doing the stats part)

Update statistics/data analytics:
- [ ] Writeup
- [ ] Picture
